"""Add progress and error_message fields to AudioFile

Revision ID: 21ff30e0d3a5
Revises: 09e0fb3f5111
Create Date: 2025-05-17 11:29:22.310770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ff30e0d3a5'
down_revision: Union[str, None] = '09e0fb3f5111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('audio_files', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('audio_files', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_files', 'completed_at')
    op.drop_column('audio_files', 'error_message')
    op.drop_column('audio_files', 'progress')
    # ### end Alembic commands ###
