"""add_file_size_to_audio_files

Revision ID: ebc24a9539ea
Revises: e477f63fc8b8
Create Date: 2025-05-16 17:55:53.656038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc24a9539ea'
down_revision: Union[str, None] = 'e477f63fc8b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('audio_files', sa.Column('mime_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_files', 'mime_type')
    op.drop_column('audio_files', 'file_size')
    # ### end Alembic commands ###
